# Generated by Django 4.2.4 on 2024-03-23 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodtracker', '0002_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
